# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 11:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('elenco', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('tradicao', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('ultimos_jogos', models.CharField(choices=[(0, 'Derrota'), (1, 'Empate'), (2, 'Vitória')], default=1, max_length=2)),
                ('data_criado', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
