# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsimulator', '0002_auto_20160414_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='ultimos_jogos',
        ),
        migrations.AddField(
            model_name='clube',
            name='antepenultimo_jogo',
            field=models.IntegerField(choices=[(0, 'Derrota'), (1, 'Empate'), (2, 'Vitória')], default=1),
        ),
        migrations.AddField(
            model_name='clube',
            name='penultimo_jogo',
            field=models.IntegerField(choices=[(0, 'Derrota'), (1, 'Empate'), (2, 'Vitória')], default=1),
        ),
        migrations.AddField(
            model_name='clube',
            name='ultimo_jogo',
            field=models.IntegerField(choices=[(0, 'Derrota'), (1, 'Empate'), (2, 'Vitória')], default=1),
        ),
    ]
