# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsimulator', '0003_auto_20160415_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='clube',
            name='escudo',
            field=models.CharField(default='/static/futsimulator/img/default.png', max_length=200),
            preserve_default=False,
        ),
    ]
